### ISSUE TITLE
slngen target multiple folders

### ISSUE THREAD

**Issue by zgf** [microsoft/slngen#115]
Hi, 
I'd like to slngen multiple test csproj and there are placed in multiple different folders.
it looks there is no cmdlet flag to control this behavior, I have to add a dummy csproj to include all test projects.

**Comment by jeffkl** [comment]
If you're using `slngen` as a command-line tool, you should be able to specify the path to multiple projects and it will generate a SLN for them all plus their closure of project references.  You cannot currently specify multiple folders however.

https://github.com/microsoft/slngen/blob/master/src/Microsoft.VisualStudio.SlnGen/Program.cs#L213
