### ISSUE TITLE
If BuildTools 2019 is installed, slngen looks for wrong devenv.exe

### ISSUE THREAD

**Issue by fvitale13** [microsoft/slngen#121]
When both Visual Studio 2019 BuildTools and Enterprise are installed, invoking slngen looks for devenv.exe in the following path:

"c:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\devenv.exe"

![slngen-BuildTools](https://user-images.githubusercontent.com/13650942/77578554-f81c2d00-6e95-11ea-859c-bcbc34d54734.png)

**Comment by jeffkl** [comment]
Blocked by https://github.com/microsoft/MSBuildLocator/issues/68 at the moment.  I'll try and get that issue fixed otherwise I have to abandon MSBuildLocator all together.

**Comment by jeffkl** [comment]
The only workaround for now is to specify the path to `devenv.exe` that you want to use.
