### ISSUE TITLE
Solution file generation for multiple projects inside a Cake-Build Script

### ISSUE THREAD

**Issue by janniksam** [microsoft/slngen#128]
Our current build process is initially generating a solution file set of projects (entry points). That is, because our developers are developing in smaller solutions to keep the load times etc. decent. But during build we want to merge all our projects together and build one big solution.

That's why we create a CreateSln.ps1-PowerShell-Script for this task. Our build script begins by calling this script. The script will get a configuration file, where we listed all our "entry points" and will resolve and add all project references. When that is done, all *Test-projects and dependencies will also be added.

Our main problem currently is that the solution file is not a 100% conform to the standards and whenever we open it in Visual Studio, a lot of stuff is automatically changed by Visual Studio again, especially some project related guids.

------

Now that I have already talked a lot, let's get to my point: Right now we are looking for an alternative and I was wondering if this tool might fit our needs. Taking a quick glance into the documentation, unfortunately I cannot see any possibility to generate a solution file for not one but many project, is there a way?

Further more I would like to know: We would like to initiate the "solution generation" somewhere in our build script. Currently our build process is based on "Cake Build". We can reference the nuget package in our cake script, but I am not sure yet, how we would get the tool to run.

**Comment by janniksam** [comment]
By the way:

It would be cool, if the core part of this tool (the solution/project models, the SlnFile.Save() logic) be extracted to a seperate package, because it would be nice to be able to use it without the other parts of this tool. I could just feed in all my projects and use this models to help me build a correct solution file.

**Comment by jeffkl** [comment]
You should be able to specify the paths to multiple entry projects for solution generation:

```cmd
slngen src\ConsoleApp\ConsoleApp.csproj test\UnitTest1\UnitTest1.csproj
```

**Comment by jeffkl** [comment]
@janniksam have you had a chance to try this out?  Does it do what you want?

**Comment by janniksam** [comment]
I did rewrite the sln generation logic in one of my powershell scripts, so this is resolved.
