### ISSUE TITLE
How to skip including some projects when generate solution file?

### ISSUE THREAD

**Issue by zgf** [microsoft/slngen#133]
I'd like only to put a specific project and its dependency on the solution base on a text filter pattern.
for example, slngen will put dirs.proj and its dependency to dirs.sln but it will skip all projects which match the pattern "*.campaign.*"

**Comment by jeffkl** [comment]
You need to set the `ShouldIncludeInSolution` property documented here:

https://github.com/microsoft/slngen/blob/master/docs/README.md#customize-the-solution-file

I've also updated the FAQ with an example:

https://github.com/microsoft/slngen/blob/master/docs/FAQ.md#how-do-i-leave-projects-out-of-the-solution
