### ISSUE TITLE
PlatformNotSupportedException

### ISSUE THREAD

**Issue by msft-mw** [microsoft/slngen#145]
Got a `PlatformNotSupportedException` thrown trying to use this tool. The actual error text was:

```
Accessing a hash algorithm by manipulating the HashName property is not supported on this platform. Instead, you must instantiate one of the supplied subtypes (such as HMACSHA1.)
```

The project was created in Ubuntu WSL1 using `dotnet new console`, but the `slgen` was run from Powershell Core in Windows. The version of `dotnet` in both cases was `3.1.301`. It did seem to create a valid solution file that was open-able in VS2019 16.6.2

**Comment by jeffkl** [comment]
Thanks for reporting this, a fix will be out shortly
