### ISSUE TITLE
Folder structure is ignored by root project

### ISSUE THREAD

**Issue by Portikus** [microsoft/slngen#151]
Hi,

I'am using the following command parameters:

slngen  --folders:true --solutionfile:.\MySolution.sln .\Folder1\Folder2\SomeProject\SomeProject.csproj 
See repro.cmd in attached repro: [Repro.zip](https://github.com/microsoft/slngen/files/4993980/Repro.zip)

I would expect that all project are sorted under SolutionFolders, but as you can see in the attached image the root project is not under any folder. Is this a bug or a not supported feature? 

![image](https://user-images.githubusercontent.com/15127750/88784010-cdb5e580-d18f-11ea-8aea-14309e2e9a86.png)

Thank you for your Help

**Comment by jeffkl** [comment]
This is by design at the moment.  This is because the "main" project that you generate a solution for is considered what you'll be working on the most and so its not stuffed under a folder.

We could add a feature to disregard the "main" project though.  Feel free to contribute!

**Comment by Portikus** [comment]
Ah okay. In our structure the main project could be just a exe with a bootstrapper.
Could you give me a hint where I could add this kind of feature?

**Comment by jeffkl** [comment]
Sure thing, this is where we determine the main project:

https://github.com/microsoft/slngen/blob/71aacfbd507b32c7a793f7b2556c61ae0ba24219/src/Microsoft.VisualStudio.SlnGen/Program.cs#L307

The last parameter, `project.FullPath` ends up being the main project which is passed around: https://github.com/microsoft/slngen/search?q=ismainproject&unscoped_q=ismainproject

You could add a command-line argument like `--nomainproject` which just stops passing that in or ignores it when building the hierarchy.
