### ISSUE TITLE
Have a similar project

### ISSUE THREAD

**Issue by zebmason** [microsoft/slngen#152]
[ProjectIO](https://github.com/zebmason/ProjectIO) reads various Visual Studio project files and probably has version issues with those. It also reads CMake projects and will create Visual Studio solutions for them. It's main purpose is to help feed ASTs (from ClangSharp or Roslyn) into [DeepEnds](https://www.deepends.co.uk) which has used various Microsoft projects on GitHub as test data - typically for deletion of dead code.

Might be worth sharing code but I currently intend to fly abroad on my hols in a few days time so not sure when I'll be able to evaluate your codebase. In the meantime feel free to evaluate ProjectIO if it is of interest.

**Comment by jeffkl** [comment]
Thanks, seems interesting.  Does Visual Studio load CMake projects out-of-the-box or do you also generate an MSBuild project?

I'm all for sharing code, please elaborate more on what you'd want to do and I can tell you if its worth it.

**Comment by zebmason** [comment]
It parses the base CMakeLists.txt file and optionally takes the CMakeCache.txt file. The code uses callbacks to do useful stuff like write details to the console or create a set of projects for DeepEnds to analyse. So I might add different callback classes to work with the slngen data structures potentially.

**Comment by jeffkl** [comment]
Closing this for now.  I think ProjectIO is more about translating CMake to Visual Studio solution files, where as SlnGen is about translating MSBuild project sets to Visual Studio solution files.
