### ISSUE TITLE
Add an option to search for projects in subdirectories as well

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/slngen#171]
It would be great if we could leverage slngen to keep our solution files up-to-date dotnet/runtime in which we have the following project hierarchy:

```
- System.Runtime.Serialization.Formatters
  - ref
      System.Runtime.Serialization.Formatters.csproj
  - src
      System.Runtime.Serialization.Formatters.csproj
  - tests
      System.Runtime.Serialization.Formatters.Tests.csproj
```

By default slngen only searches for project files in the current directory if one isn't specified. Can we change this so that it searches for project files in subdirectories as well either by default or under a switch?

Note that we would probably need multiple entry points here as we don't have a clear dependency chain yet between ref, src and test projects.

cc @jeffkl

**Comment by ViktorHofer** [comment]
cc @Anipik @ericstj just FYI so that you know that I'm currently experimenting with leveraging slngen to keep our solution files up-to-date (with our ever changing dependencies).

**Comment by jeffkl** [comment]
Generally for this type of layout, we recommend people use a Traversal project which lets you create projects in a folder that just specifies what projects to build when building that folder.  Large repos internal to Microsoft use this pattern, so there's not a lot of overhead.  Adding this pattern later can be a bit of work.  What do you think would be best?  Adding a `dirs.proj` lets you build from any folder as well as generate solutions, adding subdirectory support to SlnGen only does the later.

**Comment by ViktorHofer** [comment]
We would still want to check the generated solution file in for multiple reasons. Having both a dirs.proj and the solution file in the leaf seems redundant :/

**Comment by jeffkl** [comment]
What about not having any solution files checked in at all?  That's what large internal repos do.  Then you just generate a solution on the fly when you want to load a set of projects.

**Comment by ViktorHofer** [comment]
Can we generate solution files with slngen cross-plat and outside of the Dev Command Prompt?

**Comment by jeffkl** [comment]
Sort of, things get a little crazy when using .NET Core exclusively to evaluate projects since .NET Core SDK doesn't ship with enough logic to parse all projects (ie vcxproj).  But SlnGen only generates a solution file which is only usable by Visual Studio on Windows right?  Are users using SLN files cross-plat?

**Comment by ViktorHofer** [comment]
> Are users using SLN files cross-plat?

Yes, sln files for our libraries are used cross-plat (VS, VS4Mac, VSCode). We recently thought about switching to slnfs but didn't make the move as VS4M didn't support them.

> Sort of, things get a little crazy when using .NET Core exclusively to evaluate projects since .NET Core SDK doesn't ship with enough logic to parse all projects (ie vcxproj).

FWIW we only care about managed projects (csproj, fsproj, vbproj).

**Comment by jeffkl** [comment]
Spoke offline, I'll be adding a new command-line argument to specify a maximum depth of subdirectories to walk looking for projects.

**Comment by AraHaan** [comment]
Also JetBrains Rider can load vcxproj projects even on MacOS. Just pointing this out.

**Comment by jeffkl** [comment]
@AraHaan at this time I'm pretty swamped working on [NuGet's central package management](https://github.com/NuGet/Home/issues/11952) so it won't be on my radar for a few weeks.  Please feel free to contribute if you have the time.

**Comment by michael-hawker** [comment]
Globbing (`**\*.csproj`) seems to work well here, though there's no option to configure the structure of solution itself. It just uses the folder structure if you use the existing `--folder true --collapsedfolders true` settings.

**Comment by jeffkl** [comment]
Recent versions of SlnGen support this by specifying a globbing pattern like `**\*.csproj`.  You can also exclude globs with:

`slngen **\*.csproj --exclude:"**\*Test.csproj`

For more advanced scenarios like mapping globs to solution folders, let's open a new issue to track that.
