### ISSUE TITLE
Specify folder name as a solution file customization per project

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/slngen#179]
In the case where ` --folders <true>` is false (or the msbuild property `SlnGenFolders`), it would be great to be able to specify the solution folder per project similar to how `IncludeInSolutionFile` works.

That would allow dotnet/runtime to use to slngen to group our projects in the following hierarchy:
- ref
- src
- tests

**Comment by jeffkl** [comment]
Seems like a decent feature.  My only concern is around nesting.  Would users get to specify paths like `src\Common` and `src\Logging` or just a single path?

**Comment by ViktorHofer** [comment]
Nesting is not required for our use-case but nice to have if it would be as simple as splitting on directory separator chars.

**Comment by jeffkl** [comment]
Fixed in #185
