### ISSUE TITLE
Sharing code with dotnet-sln command

### ISSUE THREAD

**Issue by am11** [microsoft/slngen#194]
[`dotnet-sln`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln) command has its own backend for SLN emitter: https://github.com/dotnet/sdk/blob/master/src/Cli/Microsoft.DotNet.Cli.Sln.Internal/SlnFile.cs. It was originally ported from monodevelop https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/SlnFile.cs couple of years ago https://github.com/dotnet/cli/pull/4870.

It would be nice if these implementation are unified via a single nuget package, in anticipation of consistent user experience across IDEs and command line tools.

cc @dsplaisted

**Comment by jeffkl** [comment]
Yeah originally I was going to use the SlnFile class in .NET but its "internal" and the library it lives in isn't compiled for .NET Framework.

I'm open to using a library for reading/writing the solution file though.

**Comment by am11** [comment]
Which way would be best to extract out the read/write mechanics in the form of a nuget package:

* slngen repo creates a library package for dotnet/sdo and mono/monodevelop.
* dotnet/sdk or monodevelop provide a library package.

From a quick look, some aspects (like `MinimumVisualStudioVersion`) seems to be missing from slngen.

**Comment by jeffkl** [comment]
Closing for now since its going to be really hard to share code with the .NET SDK.
