### ISSUE TITLE
Redundant solution root folder created

### ISSUE THREAD

**Issue by dsbenghe** [microsoft/slngen#196]
We are using slngen extensively with the option --folders:true.

Our solutions are always generated with a redundant root folder which contains all the other solutions folders. This is especially annoying when the top folder is the root folder of the repository.

Are we doing something wrong? Is that on purpose? As we don't see too much of a point in having that redundant root folder.

**Comment by jeffkl** [comment]
Can you give me an example of the directory structure?  Do you have a root folder that just contains folders and projects and that's being reflected in the solution?

**Comment by dsbenghe** [comment]
Our structure;
/Root
//Folder1
///Folder11
///Folder12
//Folder2

The structure, having all the *.csproj in the folders and none in the root, generates same structure in the sln with the redundant /Root folder at the top which contains just the subfolders.

Basically, in our case there is always a single top root folder with content (sub-folders and/or projects) - and I don't see the point of it.

**Comment by craigktreasure** [comment]
Yep. I'm seeing the same. `/Root` in my case is the root of my Git repository. When generating using `--folders:true`, I end up with a solution that has all of my projects under a "Root" solution folder.

**Comment by stijnherreman** [comment]
I'm also seeing this.

Folder structure:
```
MyProject
├───.vscode
├───src
│   ├───Foo
│   ├───Bar
│   └───Baz
└───tests
    ├───Foo.IntegrationTests
    ├───Bar.Tests
    └───Baz.Tests
```

Command:
```
dotnet slngen --solutionfile:MyProject.sln --folders:true --collapsefolders:true --ignoreMainProject src\*\*.csproj tests\*\*.csproj
```

Output:
```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyProject.Foo", "src\Foo\MyProject.Foo.csproj", "{5449071F-A8E6-4557-B674-104700F02810}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyProject.Bar", "src\Bar\MyProject.Bar.csproj", "{E2C15F5C-184E-4A7F-BD34-C9B5EEBD81F7}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyProject.Baz", "src\Baz\MyProject.Baz.csproj", "{A3F7819C-4288-4CBE-9A4C-0AB5EA1B2121}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyProject.Foo.IntegrationTests", "tests\Foo.IntegrationTests\MyProject.Foo.IntegrationTests.csproj", "{815F96E5-FE2A-4D2E-915E-21732386B246}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyProject.Bar.Tests", "tests\Bar.Tests\MyProject.Bar.Tests.csproj", "{EEFB05CA-9830-49A1-B74F-741755971331}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyProject.Baz.Tests", "tests\Baz.Tests\MyProject.Baz.Tests.csproj", "{6A7449B7-F6F4-4BD2-8EB1-48B42D3360C9}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{9AEB43D4-EE69-4204-B67D-54BC02846544}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "tests", "tests", "{3A6DF190-0E82-4482-91F2-B6097FFAFFE2}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "MyProject", "..\MyProject", "{264EC3DD-93A1-4ADE-85A1-F3E53BF761D9}"
EndProject
```
![image](https://user-images.githubusercontent.com/1618054/142041349-e5cba07b-abaf-4b64-8e69-4aae2b2cd432.png)

I would rather not have the `"MyProject", "..\MyProject"` entry.

**Comment by jeffkl** [comment]
The "collapse" feature only runs for nodes with a single child, since MyProject has an `src` and `test` folder it won't get collapsed.  I wonder if we should add a feature where you can specify that a particular folder should be collapsed.

In the above example, you'd expect to see two top-level folders?

```
├─ MyProject\src
│   ├───Foo
│   ├───Bar
│   └───Baz
└─ MyProject\tests
    ├───Foo.IntegrationTests
    ├───Bar.Tests
    └───Baz.Tests
```

I'm not sure what the best way to convey that is...  Do you want to open a new issue to discuss?

**Comment by jeffkl** [comment]
I think the collapse logic should be updated to collapse a folder if it only contains folders and no projects.  Looking for community contributions if anyone is interested...

**Comment by stijnherreman** [comment]
@jeffkl sorry for not getting back earlier.
I was thinking there must users depending on the current behaviour. So maybe a new configuration parameter is best to change this behaviour? 

> In the above example, you'd expect to see two top-level folders?

Yes, just `src` and `test` as top-level folders.

**Comment by jeffkl** [comment]
Yeah then I think the correct logic is to not just collapse folders with a single child, but any folder with children that are only folders.
