### ISSUE TITLE
Slngen fails after specifying sdk section in global.json

### ISSUE THREAD

**Issue by ninzavivek** [microsoft/slngen#229]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/vivekagg/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/vivekagg/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/vivekagg/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>

<p class=MsoNormal>We recently modified our global.json (repo root) as follows
(highlighted, sdk version) to enforce devs and builds to use same version of
.net core.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

old | new
-- | --
{     "msbuild-sdks": {         "Microsoft.Build.CentralPackageVersions": "2.0.79",       "Microsoft.Build.NoTargets":   "2.0.1",       "Microsoft.Build.Traversal":   "3.0.2"     },   } | {     "msbuild-sdks": {         "Microsoft.Build.CentralPackageVersions": "2.0.79",       "Microsoft.Build.NoTargets":   "2.0.1",       "Microsoft.Build.Traversal":   "3.0.2"     },     "sdk":   {         "version":  "3.1.410",         "rollForward": "disable"       }   }

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><b>Issue: slngen has stopped working. It seems it is looking
for NET.SDK version , which it can find. <o:p></o:p></b></p>

<p class=MsoNormal><b><o:p>&nbsp;</o:p></b></p>

<p class=MsoNormal><b>Build seems to work, and also seems happen to be on newer
version [<span style='background:lime;mso-highlight:lime'>SlnGen version
5.0.5+a35108ec43 for .NET Core</span>] . I have a machine with [<span
style='background:lime;mso-highlight:lime'>SlnGen version 4.5.0+0f3e272a24 for
.NET Framework</span>] and that seems to work.<o:p></o:p></b></p>

<p class=MsoNormal><b><o:p>&nbsp;</o:p></b></p>

<p class=MsoNormal>I also investigated following link: <a
href="https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019</a><o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>C:\Users\vivekagg\.nuget\packages\microsoft.build.traversal\3.0.2\Sdk\Sdk.props(15,3):
warning MSB4242: The SDK resolver
&quot;Microsoft.DotNet.MSBuildSdkResolver&quot; failed to run. Method not
found: 'Microsoft.Build.Framework.SdkResult Microsoft.Build.Framework.SdkResultFactory.IndicateSuccess(System.String,
System.String,
System.Collections.Generic.IDictionary`2&lt;System.String,System.String&gt;,
System.Collections.Generic.IDictionary`2&lt;System.String,Microsoft.Build.Framework.SdkResultItem&gt;,
System.Collections.Generic.IEnumerable`1&lt;System.String&gt;)'.<o:p></o:p></p>

<p class=MsoNormal>MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be
found.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Unfortunately, MSDN link for global.json doesn’t provide
much info about its schema either : <a
href="https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x">https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x</a><o:p></o:p></p>

</body>

</html>

**Comment by jeffkl** [comment]
This is pretty tricky.  SlnGen needs to load MSBuild and its dependencies in order to evaluation projects.  One of those dependencies changed its public interface between .NET Core 3 and .NET 5:

https://github.com/dotnet/msbuild/pull/5501

Most of the dependencies can be loaded from the correct location, except the SDK resolver since its loaded relative to MSBuild which in this case is part of the VS install.

Although SlnGen is a .NET 5 app, it tries to use the MSBuild that comes with Visual Studio to have a better chance of loading project types that don't ship with .NET Core (ie C++, Service Fabric, Azure SDK).  But based on your global.json, its trying to load an older SDK with a newer SDK resolver which changed and causes this exception.

Can you pin your global.json to a .NET 5 version of the SDK?

**Comment by ninzavivek** [comment]
Just to make sure I understand this correctly, the newer version of slngen (.NET Core 5) is not compatible with code built using .NET Core 3 due to the change in public interface, right?

Unfortunately, we can't switch to .NET 5 yet. 

Does this  mean we need to switch back to using an older version of slngen?
