### ISSUE TITLE
Preserve folder GUIDs when updating a SLN.

### ISSUE THREAD

**Issue by ericstj** [microsoft/slngen#238]
Today when we run SLNGen on projects in dotnet/runtime it creates a ton of churn due to re-GUIDing all the SlnFolders.

For example: https://github.com/dotnet/runtime/commit/a6b9a63f3521d8217c3639aefd97001287f78ae8#diff-ac5f14aedd275460970bcd5cbb362a41f5cb94bd5e83402eea3fd5c9328eb954R14

It'd be nice if that diff wasn't so noisy.  I see that project GUIDs are preserved via https://github.com/microsoft/slngen/blob/d261186bcd01b3a0c8c350b2a19611032778fd17/src/Microsoft.VisualStudio.SlnGen/SlnFile.cs#L92

It'd be nice if the same could be done for folder Guids.

**Comment by jeffkl** [comment]
I agree, this should be done so the churn is low. I’ll work on this next week!

**Comment by ViktorHofer** [comment]
Note to myself: Whenever this is ready, update slngen in dotnet/runtime and re-generate the solution files to inspect the diff.
