### ISSUE TITLE
SlnGen tool argument syntax changed around version 6

### ISSUE THREAD

**Issue by smflorentino** [microsoft/slngen#252]
I updated slngen from 5 to 6 and noticed that `:` no longer works in arguments - and `projectfile` has disappeared, for instance. This doesn't match the GH pages docs. I'm happy to submit a PR, just wanted to see if that was intentional.

Also, surprised it wasn't in the release notes for version 6.
![image](https://user-images.githubusercontent.com/3495150/129939157-3f985283-67b8-4d39-a56e-5e5b2349d483.png)

Snipped from `slngen --help`:
![image](https://user-images.githubusercontent.com/3495150/129939288-479565dd-6549-4a63-afc3-3e08c9820879.png)

**Comment by jeffkl** [comment]
This must have been an oversight.  The `:` still works in version 6, it just appears to be missing from the usage.  It seems like the command-line argument parser we're using supports the `:` or not so I these both work:

```
slngen --launch false
slngen --launch:false
```

Are you seeing otherwise?  Any contribution is always welcome!

**Comment by smflorentino** [comment]
Looks like they both still work. Is there a preference on syntax (I prefer the `:` personally to help avoid spaces) - that would drive whether to update the help text or the docs, I presume.

**Comment by jeffkl** [comment]
I agree that the `:` is more declarative and easier to read, so I think we should see if we can update the usage to match the docs.
