### ISSUE TITLE
Microsoft.VisualStudio.SlnGen.targets references tools\net46\slngen.exe path that doesn't exist

### ISSUE THREAD

**Issue by snorrk** [microsoft/slngen#260]
Microsoft.VisualStudio.SlnGen.targets references "tools\\**net46**\\slngen.exe" but should reference "tools\\**net461**\\slngen.exe".

Microsoft.VisualStudio.SlnGen.targets:

``
  <UsingTask TaskName="Microsoft.VisualStudio.SlnGen.Tasks.SlnGenToolTask"
             AssemblyFile="$([MSBuild]::ValueOrDefault('$(SlnGenAssemblyFile)', '$(MSBuildThisFileDirectory)..\tools\net46\slngen.exe'))"
             Condition="'$(MSBuildRuntimeType)' == 'Full' And '$(MSBuildToolsVersion)' != 'Current'" />
``

Dir of _tools_ directory:

**net461**
net472
net5.0
net6.0
netcoreapp3.1

**Comment by jeffkl** [comment]
@snorrk thanks for finding this, I'll fix it right away!
