### ISSUE TITLE
Option to ignore PATH msbuild on Windows

### ISSUE THREAD

**Issue by tokizr** [microsoft/slngen#278]
Hello, we are using SlnGen for some of our solutions in our company but we found problems with some users who have msbuild on their `%PATH%` (we are using .Net Core).

One of our colleagues had an older msbuild that failed at the start with `MissingMethodExeception` on `Microsoft.Build.ProjectCollection..ctor(...)`. Another had mono on his `PATH` and that brings in `msbuild.bat` which also fails because it's not a Dll.

I was browsing source and I noticed SlnGen always tries to use msbuild.exe if it's found when running on Windows. It would be great if that could be disabled via some command line option.

Ideally anyone should be able to generate the solutions without having to modify their PATH or anything like that.

For now we are using a modified build that removes the `msbuild.exe` check, but we would rather use an official version.

**Comment by tokizr** [comment]
Hi, it's been a while but I finally got around to testing this.

This problem still occurs for guys that had VS2017 msbuild on their path. It seems that version only has the `ProjectCollection` constructor ending with a single boolean. In `Microsft.VisualStudio.SlnGen/Program.cs:340` I see that that version is used for net461, but `Microsft.VisualStudio.SlnGen.Tool/Program.cs` never selects that option; it is hardcoded to net472 on line 55.

vs2017 has msbuild version 15.1 (same as vs2019 from what I can tell, though different product), but the file version itself is 15.9 (in vs 2017.9.41 I have installed). In vs2019 the file version is 16.11. So you could use the file version to differentiate which runtime to select.

**Comment by jeffkl** [comment]
@tokizr Can you open a new issue?  You're right, when MSBuild 15.X is used, SlnGen tries to use MSBuild 16.X APIs.  We should be able to detect the version of MSBuild.exe and use the corresponding version of SlnGen.
