### ISSUE TITLE
Projects are not loaded when the code is in network mapped drive

### ISSUE THREAD

**Issue by viveknuna** [microsoft/slngen#305]
I have installed the tool by running the below command yesterday.

`dotnet tool install --global Microsoft.VisualStudio.SlnGen.Tool`

Then I run the below command to generate the solution.

```
@ECHO OFF
slngen --launch:false --folders:true --collapsefolders:true --solutiondir:src --solutionfile:MySolution.sln --ignoreMainProject --verbosity:normal **.csproj **.sqlproj
REM --verbosity:diag
```
It works as expected when my code is in C drive, But when my code is in J drive which is a network drive.  It gives the below errors when I open the solution in Vishal Studio 2019.

> One or more projects in the solution were not loaded correctly. Please see the Output window for details.

**Error in the output window.**

> J:\folder\UNC\SUKWGWGDSPASDF1\VDIUsers$\User.Name\folder\src\shared\Common\MyProject.Common.csproj : error : The project file cannot be found.

How to fix it? I have to use the J drive, It's required.

**Comment by viveknuna** [comment]
@jeffkl sure, thank you for responding, I'll wait for the update.

**Comment by viveknuna** [comment]
@jeffkl It's working as expected. Thank you

**Comment by jeffkl** [comment]
Thanks for reporting the issue, luckily the fix was easy!
