### ISSUE TITLE
Consider creating a .NET Core global tool

### ISSUE THREAD

**Issue by dfederm** [microsoft/slngen#31]
See: https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility

So calling something like "dotnet slngen"

Although this is very similar to the existing "dotnet sln" command already.

**Comment by jeffkl** [comment]
Technically SlnGen uses some special stuff because its run as an MSBuild task.  So a dotnet tool would simply need to run `dotnet msbuild /t:SlnGen` to get the correct outcome.
