### ISSUE TITLE
Feature to include njsproj file with slngen

### ISSUE THREAD

**Issue by ajithkumarmcw** [microsoft/slngen#335]
I am able to include C#(.csproj) and C++ project(.vcxproj) files successfully but after including .njsproj files it is throwing error when i open the solution file i face a error 
`C:\Users\Ajith\Documents\project\Sample\SampleNode\SampleNode\SampleNode.njsproj : error  : The build project should have been initialized before calling PreCreateForOuter.`

![snap_build_config](https://user-images.githubusercontent.com/84714146/156620122-7b2e51a7-ab86-4b27-a586-0346c10aa837.JPG)
![snap_nodeproject](https://user-images.githubusercontent.com/84714146/156620102-951f67d1-e25c-4ce0-ac5a-00a0c7d81f80.JPG)

Is that feature added to slngen ? if so could u kindly advise a solution for it ?

Below is the command and project built.
`slngen -o Test.sln SampleNode`
https://github.com/ajithkumarmcw/NodeProject

**Comment by jeffkl** [comment]
Can you please try removing the project from the solution and re-adding it in Visual Studio?  I'd like to see what Visual Studio places in the `.sln` file and maybe SlnGen just needs to use a different project type GUID or something?

**Comment by ajithkumarmcw** [comment]
Yes it works when i remove and add , Also it works when i change the GUID manually, so is there any fix to do it with slngen itself ?

**Comment by ajithkumarmcw** [comment]
I tried the option of setting custom "https://microsoft.github.io/slngen/" Custom GUID , but it includes njsproj file also in VS.
 
![snap_njsproj](https://user-images.githubusercontent.com/84714146/157226524-2a3338a8-f9a3-4b59-b5b1-2dc2abf13319.JPG)

i did below code change
```
  <ItemGroup>
    <Content Include="app.js" />
    <Content Include="package.json" />
    <Content Include="README.md" />
    <SlnGenCustomProjectTypeGuid Include=".njsproj" ProjectTypeGuid="{9092AA53-FB77-4645-B42D-1CCCA6BD08BD}" />
  </ItemGroup>
```

**Comment by jeffkl** [comment]
SlnGen doesn't control what shows up in Solution Explorer under a particular project, only what projects appear and any solution items you configure.  I'm not sure why the `.njsproj` file is showing up there.  I'll update SlnGen to understand `.njsproj` natively.

**Comment by ajithkumarmcw** [comment]
Thanks for adding support. I have a question @jeffkl does slngen supports adding project to a existing solution file ?  (I think this feature is not present let me know if i am wrong )

**Comment by jeffkl** [comment]
SlnGen will re-generate a solution file based on the cone of projects it finds.  If you want to just add a single project to a solution you can use `dotnet sln`

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln

**Comment by ajithkumarmcw** [comment]
thanks
