### ISSUE TITLE
Adding two project with same project name

### ISSUE THREAD

**Issue by ajithkumarmcw** [microsoft/slngen#338]
Is it possible to create a solution file Work.sln with two identical project files with same name but in different folder(n-2) ?

Example:
```
 (n-3)         (n-2)          (n-1)         (n)
-Work..sln
-------------fold1
                          |--- plan
                                           |--plan.njsproj
-------------fold2
                          |--- plan
                                          |--plan.njsproj
```

In UI i would create a manual folder and then i use to include plan in that folder. Could you tell if its possible with this any option ?

I tried this option "--folders" like below but it seems to include only the plan.njsproj file

`slngen -o Work.sln --folders false allfol\fol1\plan.njsproj  all\fold2\plan.njsproj`

**Comment by jeffkl** [comment]
Try specifying `--folders:true`

**Comment by ajithkumarmcw** [comment]
No it doesnt seem to work i tried with both --folders:true and --folders:false .

**Comment by ajithkumarmcw** [comment]
Hey sorry, when i tested it today it is working for `--folders:true` . May be i made some mistake from myside yesterday. Thanks for the help.
I need a clarification on 1 minor issue.
I have tried both of the below commands
`slngen  -o TestDuplicate.sln SampleNode work\folder1\plan work\folder2\plan --folders:true`

`slngen  -o TestDuplicate.sln SampleNode\SampleNode.njsproj work\folder1\plan\plan.njsproj work\folder2\plan\plan.njsproj --folders:true`

for this repo https://github.com/ajithkumarmcw/NodeProject from root folder,

it give a UI like below snapshot
where "work\folder2\plan" goes out of the root dir "NodeProject" because already there is a project in "work" folder

![snap_dirsturcture](https://user-images.githubusercontent.com/84714146/157906406-3959ce47-03c3-454a-a567-15adc3110bd7.JPG)

Is there any way to control it to come like below structure
```
NodeProject
                    |---SampleNode
                    |---work/folder1/plan
                    |---work/folder2/plan

```

**Comment by jeffkl** [comment]
With folders enabled, SlnGen wants to treat one of them as the "main" project.  So the first project you specify will show up in the root with everything else going in folders.

**Comment by ajithkumarmcw** [comment]
okay thanks
