### ISSUE TITLE
How do I set the main project?

### ISSUE THREAD

**Issue by nathansoz** [microsoft/slngen#339]
Consider the following scenario:

I have a Web API project that I want to be the "main project." This project should be the startup project in VS. I also have test projects that I want to load. I have a solution hierarchy that looks like:

```
/project/A/dirs.proj
/project/A/src/
/project/A/test/
```

Presumably I should run slngen on /project/A/dirs.proj. But how do I tell slngen that a specific project in src should be the "main" project? If I run slngen explicitly on the main project then I don't get the unit test projects included.

**Comment by jeffkl** [comment]
At the moment, the "main" project is the first project.  If you run slngen against the unit test project, the project it tests will be included but the unit test project will be the main one.  Traversal projects (dirs.proj) are left out of the solution so they don't really show up as the main project.  It is not possible at this time to specify which project should be the main one.  I think its only applicable if you're using solution folders as the main project will show up at the root.  If you're not using solution folders all of the projects just show up alphabetically.

**Comment by nathansoz** [comment]
> I think its only applicable if you're using solution folders as the main project will show up at the root. If you're not using solution folders all of the projects just show up alphabetically.

I guess I'm equating Startup project and the Main project. Maybe they are the same thing? What I would like to accomplish is specifying what project F5s by default in VS.

**Comment by jeffkl** [comment]
@nathansoz ah so I was told by the Visual Studio team that there isn't really a good way to create a solution and tell VS what is the "startup" project, unfortunately.  If we ever find a way, I'll gladly add support for it in SlnGen.

**Comment by nathansoz** [comment]
Ah ok! Thanks for the quick reply. I'll close this out and hope the VS team can add it in the future.
