### ISSUE TITLE
Is there a way to define files to be included?

### ISSUE THREAD

**Issue by msft-mw** [microsoft/slngen#340]
My repo has a lot of loose files (build definition yaml files, etc) that I'd like to see included in the generated solution. I looked through the documentation but nothing stood out to me as a way to do this. Does it exist as a feature?

**Comment by jeffkl** [comment]
Yes!  You can include these files in the solution by specifying `SlnGenSolutionItem` items

https://github.com/microsoft/slngen/blob/main/docs/README.md#configuring-slngen

```xml
<ItemGroup>
  <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)global.json" />
  <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)README.md" />
</ItemGroup>
```
