### ISSUE TITLE
Console is 'held hostage' when launching Visual Studio with SlnGen 8.0+

### ISSUE THREAD

**Issue by richardsondev** [microsoft/slngen#342]
In 1ES Test, we are currently using SlnGen 2.2.8.  While upgrading to SlnGen 8.0 or higher, we are seeing the same outcome as #203 when NOT specifying `SlnGenDevEnvFullPath`.

When launching `msbuild /t:SlnGen` the console is held until Visual Studio 2022 is exited. Once Visual Studio is exited, MSBuild finishes, and the console is unlocked. 

If I switch to SlnGen 7.2.3, then the console is properly released even when Visual Studio is still running.

I see that the UseShellExecute property was removed in the latest versions of SlnGen so we cannot alter this property to try and workaround this issue.

Is there another property we can set so that the console is not held hostage when VS is still running?

Should we just use 7.2.3 since it works ok in our case? (We are fine with using an older version but would like to use the latest if possible)

**Comment by jeffkl** [comment]
@richardsondev are you able to use the .NET global tool instead?  The target-based SlnGen is running as an MSBuild target so I'm not 100% sure I'll have time to look into fixing this with a breakaway process in this context.  I know the global tool works better.

https://github.com/microsoft/slngen/#getting-started---net-core-global-tool-recommended

**Comment by richardsondev** [comment]
Yes, we can look into the global tool. Thanks @jeffkl!

**Comment by richardsondev** [comment]
Hey again! For what it's worth, I built SlnGen 8.3 locally and changed the VS launcher to use `UseShellExecute = true` and the issue was resolved with the target-based solution (MSBuild finished as expected after VS was launched).

I also played around with the other configurations (like RedirectStandardOut, etc) but did not make any progress as long as `UseShellExecute = false` (MSBuild was always stuck while VS was open).

Is there any plan to bring back the UseShellExecute configuration?

I will continue to push the team to use the global tool (and may even edit our local SlnGen target to just output a message like `Please use the global tool`.)

**In any case, please feel free to close the bug.** I just wanted to reach out and see if there was any guidance and using the global tool works with us 👍

**Comment by jeffkl** [comment]
I tested it out and it seems to be fine so I'm going to change it.  Thanks for reporting the issue

https://github.com/microsoft/slngen/pull/348
