### ISSUE TITLE
Installing slngen on a machine with .NET 7 leads to unactionable error messages

### ISSUE THREAD

**Issue by jaredpar** [microsoft/slngen#359]
Earlier today I attempted to use slngen on a machine with .NET 7 SDK installed and was immediately hit with the following error: 

```
C:\Users\jaredpar\code> dotnet tool install --global Microsoft.VisualStudio.SlnGen.Tool
You can invoke the tool using the following command: slngen
Tool 'microsoft.visualstudio.slngen.tool' (version '8.4.1') was successfully installed.
C:\Users\jaredpar\code> slngen
The .NET SDK 7.0.100-preview.2.22153.17 is not supported
```

This lead to several threads with the .NET CLI team, rounds of debugging the roll forward status of the binaries, trying use `--framework` during install to pick other targets. 

Someone finally looked at the SLNGEN code and found this line which appears to be the culprit: 

https://github.com/microsoft/slngen/blob/8ba9b23b1fa6ad1a564285fecfe43bddb425fa0a/src/Microsoft.VisualStudio.SlnGen.Tool/Program.cs#L74

It's unclear why this exists but the end effect of this is it leaves users unable to use the binary and having very little idea why they're not able to.

**Comment by jeffkl** [comment]
Thanks for reporting this.  I've added support for .NET 7 and improved the error message in version 8.5.0.

**Comment by AraHaan** [comment]
now 8.5.0 has a new error.
