### ISSUE TITLE
Custom solution hierarchy

### ISSUE THREAD

**Issue by jp2masa** [microsoft/slngen#37]
This project is really good, but I think that the generated solution is too complex.

The main problem is that projects should be grouped by folder, not project file, it's too hard to navigate on a solution where all projects are placed under a folder with the same name for no good reason...

It would also be good to be able to specify a custom path for projects, probably using some property on the project, and solution items, probably as item metadata.

Something like:
```xml
<Project ...>
    ...
    <PropertyGroup>
        <SlnGenHierarchyPath>Tests\</SlnGenHierarchyPath>
    </PropertyGroup>
    ...
</Project>
```
and
```xml
<Project ...>
    ...
    <ItemGroup>
        <SlnGenSolutionItem Include="build\Targets\**" HierarchyPath="Solution Items\build\Targets\" />
    </ItemGroup>
    ...
</Project>
```

Is this currently possible? If not, I can help implementing this.

**Comment by jeffkl** [comment]
At the moment you cannot customize the hierarchy.  I've been wanting to put in these features:

* Flat hierarch (no folders at all)
* Collapse single project folders (if a folder contains only a single folder, collapse it to something like src\foo\bar)
* Custom hierarchy

If you have time to contribute anything, please feel free!

**Comment by jeffkl** [comment]
For now we support having folders or not. Let’s re-open if more people request custom hierarchy

**Comment by icnocop** [comment]
I think https://github.com/microsoft/slngen/issues/466 and https://github.com/microsoft/slngen/pull/467 are related.

**Comment by icnocop** [comment]
A humble +1 for generating a sln file with a custom solution folder hierarchy for a set of project files (or a traversal project file).

As a work-around, here are some other tools which may allow this:
1. Run slngen multiple times for each subtree and then merge the multiple sln files into one using [dotnet-slnmerge](https://gitlab.com/dotnet-slnmerge/dotnet-slnmerge)
2. [SubSolution](https://github.com/ReMinoer/SubSolution)
