### ISSUE TITLE
Installing slngen for projects targeting .NET 6 results in slngen crash.

### ISSUE THREAD

**Issue by AraHaan** [microsoft/slngen#394]
Slngen crashes with a stack trace when using it to generate a solution for .NET 6 projects:

Command:
> dotnet slngen

Stack Trace:
> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
> File name: 'System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
>  ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at Microsoft.VisualStudio.SlnGen.Program.\<\>c.\<Main\>b__17_0(Object sender, ResolveEventArgs eventArgs)
>    at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
>    at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
>    at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary\`2 toolsets, ToolsetConfigurationReader configurationReader, PropertyDictionary\`1 environmentProperties, PropertyDictionary\`1 globalProperties, ToolsetDefinitionLocations locations)
>    at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetConfigurationReader configReader)
>    at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary\`2 globalProperties, IEnumerable\`1 loggers, IEnumerable\`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly, Boolean useAsynchronousLogging)
>    at Microsoft.VisualStudio.SlnGen.Program.Execute(ProgramArguments arguments, IConsole console)
>    at Microsoft.VisualStudio.SlnGen.ProgramArguments.OnExecute(IConsole console)
> --- End of stack trace from previous location ---
>    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
>    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
>    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.\<\>c__DisplayClass0_0.\<\<Apply\>b__0\>d.MoveNext()
> --- End of stack trace from previous location ---
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
>    at Microsoft.VisualStudio.SlnGen.Program.Execute(String[] args, IConsole console)

Version Used: 8.5.0

**Comment by jeffkl** [comment]
@AraHaan how do you have SlnGen installed?  The global tool install should be run as just `slngen` instead of `dotnet slngen`.  The global tool is a bootstrapper that determines the correct instance of SlnGen to run which should not exhibit this problem.

**Comment by AraHaan** [comment]
I have it installed as global (probably outdated on that version) and repository local to some repositories (which is the latest version).

**Comment by jeffkl** [comment]
I have this crazy bootstrapper logic which detects which instance of SlnGen will be compatible with whatever SDK you've configured:

https://github.com/microsoft/slngen/blob/main/src/Microsoft.VisualStudio.SlnGen.Tool/Program.cs

This should run, see that you're have .NET 6 in your global.json, and then run the `net6.0` SlnGen.  If you're on Windows, it will detect that you have Visual Studio installed and instead run the `net472` SlnGen.  This is because the correct instance of MSBuild must be used in order for things to work correctly.  A `net6.0` executable won't be able to load the `netcoreapp3.1` MSBuild.dll from the SDK for example.

So the global tool just targets `net5.0` and then shells out to the correct instance of SlnGen based on your environment.  The global tool takes care of this by packaging up all of the SlnGen instances.  I'm not sure how the local tool execution works.  Does it only break for the local tool vs the global tool?

**Comment by AraHaan** [comment]
Ah, the repository currently does not use global.json but it is possible for me to add one.

**Comment by AraHaan** [comment]
Alright after testing with a global.json file it still crashes with the same stack trace:

global.json:

```json
{
  "sdk": {
    "version": "6.0.100",
    "allowPrerelease": true,
    "rollForward": "latestMinor"
  }
}
```

**Comment by jeffkl** [comment]
@AraHaan can you provide some exact repro steps I can follow to see if I can figure out what's going on?  It sounds like the environment from which SlnGen is being launched is unexpected but its hard to say without know more about exactly how you're running it.

**Comment by AraHaan** [comment]
It seems with a minor change to the global.json to remove ``rollForward`` fixes it for both local and global installs of the tool. However I also think the tool should default try vswhere instead of relying on msbuild being in the path for those who prefer to not use the developer powershell / command prompt and instead use powershell core (where then the developer environment where msbuild would be in the path is not in the path).

**Comment by jeffkl** [comment]
@AraHaan thanks for reporting the issue, I finally figured out what's going on.  I will send a PR shortly

**Comment by craigktreasure** [comment]
The updated 8.5.17 package fixes the issue for me.

**Comment by jeffkl** [comment]
Thanks again for reporting the issue everyone!
