### ISSUE TITLE
Project file paths get scrambled with error MSB4025

### ISSUE THREAD

**Issue by cjahermanns** [microsoft/slngen#462]
Hi,

when I try to create a sln with the `**/*.csproj` argument, some project file paths get messed up. I tried debugging the issue and found out that the instantiation of `ProjectGraphEntryPoint` in `ProjectGraphProjectLoader.cs` line 47

```csharp
ProjectGraph projectGraph = new ProjectGraph(
                projectPaths.Select(i => new ProjectGraphEntryPoint(i, globalProperties)),
                projectCollection,
                CreateProjectInstance);
```

seems to somehow change the file path. I suspect its `ProjectFile = FileUtilities.NormalizePath(projectFile);` constructor call is the culprit but I can't verify that. I used 

```csharp
ProjectGraph projectGraph = new ProjectGraph(
    projectPaths.Select(i =>
    {
        var entryPoint = new ProjectGraphEntryPoint(i, globalProperties);

        if (!File.Exists(entryPoint.ProjectFile))
        {
            throw new FileNotFoundException();
        }

        return entryPoint;
    }),
    projectCollection,
    (path, props, collection) =>
    {
        if (!File.Exists(path))
        {
            throw new FileNotFoundException();
        }

        return CreateProjectInstance(path, props, collection);
    });
```

to find out that the `ProjectGraphEntryPoint` must have something to do with the matter.

The error says `Sources\Products\Components\Xml\Xml\Xml.csproj` could not be loaded. Which is understandable since the path should be `Sources\Components\Xml\Xml\Xml.csproj`. There is, however, another subfolder `Sources\Products` containing some other csproject files that also should be added to the new sln. I ran the tool from within the `Sources` directory.

**Comment by jeffkl** [comment]
Thanks for reporting this, I'm **very** interested in getting a repro of the problem.  Do any of your `<ProjectReference />` items contain properties like:

```xml
<ProjectReference Include="$(RepoRoot)\src\ProjectA\ProjectA.csproj" />
```

Are you able to create a ZIP that I can use to debug the issue?  I tried just:

```
slngen **/*.csproj
```

And everything worked as expected, presumably because something in the projects themselves is causing the problem.

**Comment by cjahermanns** [comment]
Hi Jeff, thank you for your response. I further investigated the issue and found one project in the repo, that indeed had wrong paths (I generate all the `<ProjectReference />` myself but my tool must have skipped this particular project because it is not in sdk style). Sorry for complaining!
