### ISSUE TITLE
Cannot build - either with our without .NET 8.0

### ISSUE THREAD

**Issue by davidair** [microsoft/slngen#476]
I tried building slngen locally but it failed to build.

Steps to reproduce:

1. cd c:\open
2. git clone https://github.com/microsoft/slngen
3. cd slngen
4. dotnet build

If .NET 8.0 is not installed, the build complains about missing .NET 8.0:

C:\Program Files\dotnet\sdk\7.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [c:\open\slngen\src\Microsoft.VisualStudio.SlnGen.UnitTests\Microsoft.VisualStudio.SlnGen.UnitTests.csproj::TargetFramework=net8.0]
C:\Program Files\dotnet\sdk\7.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [c:\open\slngen\src\Microsoft.VisualStudio.SlnGen\Microsoft.VisualStudio.SlnGen.csproj::TargetFramework=net8.0]

If I install the latest .NET 8.0 preview, it fails due to conflicts but also bunch of other weird errors:

C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Microsoft.Common.CurrentVersion.targets(2352,5): error MSB3277: Found conflicts between different versions of "System.Runtime" that could not be resolved. [c:\open\slngen\src\Microsoft.VisualStudio.SlnGen.UnitTests\Microsoft.VisualStudio.SlnGen.UnitTests.csproj::TargetFramework=net5.0]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Microsoft.Common.CurrentVersion.targets(2352,5): error MSB3277: There was a conflict between "System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [c:\open\slngen\src\Microsoft.VisualStudio.SlnGen.UnitTests\Microsoft.VisualStudio.SlnGen.UnitTests.csproj::TargetFramework=net5.0]

Unable to use package assets cache due to I/O error. This can occur when the same project is built more than once in parallel. Performance may be degraded, but the build result will not be impacted.
  
 c:\open\slngen\src\Microsoft.VisualStudio.SlnGen\Tasks\SlnGenToolTask.cs(131,63): error CA2021: Type 'System.Collections.Generic.KeyValuePair<string, string>' is incompatible with type 'System.Collections.DictionaryEntry' and cast attempts will throw InvalidCastException at runtime [c:\open\slngen\src\Microsoft.VisualStudio.SlnGen\Microsoft.VisualStudio.SlnGen.csproj::TargetFramework=net8.0]
 
 CSC : error CS2012: Cannot open 'c:\open\slngen\src\Microsoft.VisualStudio.SlnGen\obj\Debug\slngen.dll' for writing -- 'The process cannot access the file 'c:\open\slngen\src\Microsoft.VisualStudio.SlnGen\obj\Debug\slngen.dll' because it is being used by another process.' [c:\open\slngen\src\Microsoft.VisualStudio.SlnGen\Microsoft.VisualStudio.SlnGen.csproj::TargetFramework=net8.0]

Openning SlnGen.sln in VS 2022 and trying to build also fails.

I am running Windows 10 21H2 OS Build 19044.2846. I have Visual Studio 2022 Version 17.5.1

dotnet --list-sdks
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
5.0.416 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
7.0.201 [C:\Program Files\dotnet\sdk]

dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jeffkl** [comment]
This is strange, I can reproduce the problem as well but only from the command-line.  Everything builds just fine in Visual Studio.  @davidair are you able to use Visual Studio to build?  I'll try to look into this later but its not a top priority since VS works and the hosted build works.

**Comment by davidair** [comment]
I *believe* I had the same problem with Visual Studio. I just tried a clean checkout with VS 2022 17.5.4 and hit the same issue: 

_Error	NETSDK1045	The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0._

Do I need to have .NET 8.0 installed? I can grab SDK 8.0.100-preview.3 from https://dotnet.microsoft.com/en-us/download/dotnet/8.0 if it's the right framework to install.

**Comment by jeffkl** [comment]
Yes you'll need to install .NET 8 to build SlnGen at the moment.  You can also remove `net8.0` as a target framework just to build locally.

**Comment by davidair** [comment]
Thank you, I can confirm that removing references to net8.0 from the following files makes it buildable as-is in 17.5.4:

- src/Microsoft.VisualStudio.SlnGen.Tool/Microsoft.VisualStudio.SlnGen.Tool.csproj
- src/Microsoft.VisualStudio.SlnGen.UnitTests/Microsoft.VisualStudio.SlnGen.UnitTests.csproj
- src/Microsoft.VisualStudio.SlnGen/Microsoft.VisualStudio.SlnGen.csproj

Note that the latest .NET 8 preview requires Visual Studio 2022 (v17.6 Preview 1) which I don't have so I didn't test it (I believe the previous .NET 8 build I tried, which did give me grief, required 17.4 or 17.5).

In any case, removing the net8.0 target framework is a good workaround to get it to build with the my version of VS 2022 (17.5.4 - note that this is not the latest, at the time of writing 17.5.5 has already been released).

**Comment by davidair** [comment]
Appreciate the quick fix, thank you!
