### ISSUE TITLE
Place solution items in the respective folder hierarchy

### ISSUE THREAD

**Issue by ptasev** [microsoft/slngen#494]
I am using `SlnGenSolutionItem` to include solution items, however all of them are placed in the `Solution Items` folder rather than in the nested solution folders according to the file system layout. Is there an option for this currently? If not can such an option be added?

Current:
```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{0375631E-D9D5-4E7C-8D0A-C427B3720EEA}"
	ProjectSection(SolutionItems) = preProject
		tests\Directory.Build.props = tests\Directory.Build.props
	EndProjectSection
EndProject
```

Expected:
```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "tests", "tests", "{0375631E-D9D5-4E7C-8D0A-C427B3720EEA}"
	ProjectSection(SolutionItems) = preProject
		tests\Directory.Build.props = tests\Directory.Build.props
	EndProjectSection
EndProject
```

**Comment by jeffkl** [comment]
Seems like a great suggestion.  I think at the moment they items are flattened.  How are you currently specifying the items?  I wonder if we'd need a way to tell SlnGen that you want the solution items to be hierarchical.

```xml
<ItemGroup>
  <SlnGenSolutionItem Include="Directory.Build.*" />
  <SlnGenSolutionItem Include="tests\Directory.Build.*" Folders="true" />
</ItemGroup>
```

**Comment by ptasev** [comment]
Using the global tool I specify `--folders true`. For this implementation I would use a similar global setting for all solution items. In my case even using the same folder setting for both projects and solution items would be fine.

Right now if I specify the solution items as shown below all of them are flattened, and without opening the file it's tough to tell the location of the file since VS and Rider will just list them with their file name under the `Solution Items` solution folder.

```xml
<ItemGroup>
  <SlnGenSolutionItem Include="**\Directory.Build.*" />
</ItemGroup>
```

**Comment by jeffkl** [comment]
Yeah makes sense, if you specify `--folders true` the solution items should be in folders as well.  I think it would also be helpful if you didn't specify `--folders true` that solution items could be hierarchical.  Feel free to send a pull request!
