### ISSUE TITLE
Gather solution items from entire project list

### ISSUE THREAD

**Issue by ptasev** [microsoft/slngen#498]
Currently solution items are only taken from the first project in the projects list. The request is to instead get solution items from all projects in the projects list.

https://github.com/microsoft/slngen/blob/a06af1f01ca57f9a61f28707c8b839f259bd5078/src/Microsoft.VisualStudio.SlnGen/SlnFile.cs#L137-L143

**Comment by jeffkl** [comment]
The general idea was that the solution items be defined in a common import that all projects include.  But I can see why users would want different solution items for different projects.  Might as well include the union of items defined in all projects.
