### ISSUE TITLE
Feature request: Customize solution using MSBuild properties when using tool

### ISSUE THREAD

**Issue by MattKotsenas** [microsoft/slngen#503]
# Scenario

Our team runs a monorepo with 250+ `.csproj` files grouped into 65 components via `dirs.proj` files. `.sln` files are ignored via `.gitignore`. The standard workflow is for developers to create / update their branch, then run `dotnet slngen --folders true` in the appropriate folder that they're working in (using `--folders` is required because some projects in different components have the same name). Lastly, slngen automatically opens `dirs.sln` in Visual Studio and they can begin working.

# The Problem

While this workflow works, it has two pain points:

1. Requiring developers to type `--folders true` every time
2. Every Visual Studio solution window is named "dirs"

# Workarounds

There are workarounds for these problems, however they come with their own drawbacks:

## 1. Custom alias

We could create a custom shell alias for developers that uses `--folders true` and `--solutionfile`. Drawbacks:

- Developers usually need to opt-in or we need an "init" script to add aliases to the terminal session
- Aliases vary by shell (e.g. powershell, bash, fish, cmd, etc.)

## 2. Rename dirs.proj

We could avoid issue 2 by using descriptive names instead of `dirs.proj` for all dirs projects. Drawbacks:

- Devs _like_ the discoverability of knowing that `dirs.proj` defines a component

# Proposed Solution

SlnGen _has_ the customization options we want available [here](https://microsoft.github.io/slngen/#customize-the-solution-file), specifically the MSBuild properties:

- `<SlnGenFolders>`
- `<SlnGenProjectName>`

For instance, if I could create a `dirs.proj` file like this:

```xml
<Project Sdk="Microsoft.Build.Traversal">
  <PropertyGroup>
    <SlnGenFolders>true</SlnGenFolders>
    <SlnGenProjectName>MyAwesomeComponent</SlnGenProjectName>
  </PropertyGroup>
  <ItemGroup>
    <!-- Build all projects recursively -->
    <ProjectReference Include="**/*.*proj" />
  </ItemGroup>
</Project>
```

and when I run `dotnet slngen` I get a Visual Studio instance like this:

![image](https://github.com/microsoft/slngen/assets/51421/3e13aead-a0ab-4d49-bf4c-7d43fb395649)

that would solve both of our issues.

**Comment by MattKotsenas** [comment]
I'm happy to do the work here, but I wanted to reach out first and ensure that a change like this is aligned with the SlnGen roadmap. I have an _extremely_ hacky commit here: https://github.com/MattKotsenas/slngen/commit/795a14129085900fa537a835119e9b04f8a7733d that I made to convince myself this type of change was possible and it worked for my test scenario. If this proposal went forward, I'd likely suggest creating an "options" class that centralizes the calculation of `arguments` -> `MSBuild properties` -> `defaults` fallback logic.

I'm also happy to discuss my scenario further, or consider other workarounds.

Thanks!

**Comment by jeffkl** [comment]
I like the idea, feel free to contribute!

**Comment by mruxmohan4** [comment]
Closing this as this has been deployed in `v11.2.3` release.
