### ISSUE TITLE
Drop net5.0 and remove conditions from net8.0 TFM

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/slngen#513]
net5.0 went out-of-support in May, 2022. Can we remove its TFM and build support?

Also, now that net8.0 is already available as an RC (go-live) release, can we remove the `TargetsNet8` conditions?

**Comment by jeffkl** [comment]
We cannot remove net5.0 support just yet as its needed in case your repository targets .NET 5.0, SlnGen needs to use the exact same SDK to evaluate projects.  I don't know exactly when we could remove it and I'm not sure if its adding any overhead honestly.

For .NET 8, yeah now that its RC maybe we could update what SlnGen builds against?  It doesn't really matter, as what it does at runtime is find the SDK that you have installed and runs against that.  But I'm open to contributions!

**Comment by ViktorHofer** [comment]
> We cannot remove net5.0 support just yet as its needed in case your repository targets .NET 5.0

But .NET 5.0 is already out-of-support for nearly one and a half years. Do we really need to keep support for it alive? Asking as such customers could always consume previous versions of slngen on nuget.org.

**Comment by jeffkl** [comment]
I've decided to remove support for .NET 3 and .NET 5 in SlnGen 11.x: https://github.com/microsoft/slngen/pull/537

When .NET 8 is GA, I'll remove the `TargetNet8` conditions.
