### ISSUE TITLE
Support .NET 9 previews

### ISSUE THREAD

**Issue by SteveSandersonMS** [microsoft/slngen#527]
Because we're now so close to .NET 8 GA, work on .NET 8 is now happening on `release/8.0` branches and .NET's `main` branches are now generating 9.0-versioned packages.

We're running into an issue in https://github.com/dotnet/extensions/pull/4443 where the build is failing with this error from slngen:

> SlnGen does not currently support the .NET SDK 9.0.100-alpha.1.23464.17 defined by in global.json.  Please update to the latest version and if you still get this error message, file an issue at https://github.com/microsoft/slngen/issues/new so it can be added.
Exception: /mnt/vss/_work/1/s/scripts/Slngen.ps1:127

I have updated to slngen 10.3.4 but the issue remains.

Would it be possible to update slngen itself to support 9.x-versioned preview .NET builds?

**Comment by RussKie** [comment]
I attempted to add .NET 9 support in https://github.com/microsoft/slngen/pull/526, but I'm not very successful...

**Comment by RussKie** [comment]
We chatted with @jeffkl, and it looks like we are waiting on https://github.com/dotnet/installer/pull/17280...

**Comment by ViktorHofer** [comment]
Just a note, we got that change in recently and a nightly 9.0 SDK already allows targeting net9.0.

**Comment by jeffkl** [comment]
Fixed in https://github.com/microsoft/slngen/pull/544
