### ISSUE TITLE
Issue generating .sln file w/ 11.2.3

### ISSUE THREAD

**Issue by wdcossey** [microsoft/slngen#578]
This may be related to https://github.com/microsoft/slngen/pull/549

I updated SlnGen to `11.2.3` (from `10.2.0`) and now get a warning:
> SlnGen : warning : Detected folder on a different drive from the root solution path pet.sln. This folder should not be committed to source control since it does not contain a simple, relative path and is not guaranteed to work across machines.

But with the warning comes a completely different (generated) .sln file, that now has `some` absolute paths and `some` relative ones, so I am not sure that the feature that was added works as intended (or does not cover all scenarios).
FYI: We are working out of a mono-repo so there's a few projects in there with varying folder depths.

I rolled back to `10.2.0` and got the expected (generated) .sln file, then rolled-forward to `11.1.0` and that also works, so it's safe to say that the issue lay with `11.2.3`.

Any help would be appreciated.

Regards,
Will.

**Comment by mruxmohan4** [comment]
If the drive that the current project is different from the drive that the solution file is being saved to, we need to use rooted absolute paths for that project's entry. If the project is on the same drive, the path should be relative. If one or more projects are on a different drive, then this warning is emitted. Could you inform me of the specific paths (or examples) which would cause this warning to be emitted when it perhaps should not?

**Comment by wdcossey** [comment]
Hi,

Yeah I understand how the 11.2.3 update is intended to work, however it breaks (adds absolute paths) my solution file unlike the previous versions.

The solution file isn't generated to a different drive, all project folders are chilren of the solution.

I have created a sample structure that can reproduce this issue. I'll upload it to a public repo and post the link in my next comment.

**Comment by wdcossey** [comment]
As promised, here's the repo that can reproduce my issue.

https://github.com/wdcossey/slngen-test

Initial commit was using slngen `11.1.0`

Here's a PR showing the difference between `11.1.0` and `11.2.3`

**Comment by mruxmohan4** [comment]
Thanks, I was able to reproduce the issue (which oddly appeared for `11.1.0` for me as well). There may be another issue lurking here, so I will leave this issue open after an initial fix has been merged/deployed.

**Comment by mruxmohan4** [comment]
Closing this issue, as it should be resolved with `v11.2.6`.
