### ISSUE TITLE
Add flag to prevent ActiveCfg lines in solution file

### ISSUE THREAD

**Issue by ezgambac** [microsoft/slngen#67]
While working on my project, I ran into an issue where some projects where stuck in Release configuration even though the global config was debug.
Even after going into configuration manager and switching from release to debug, the change didn't stick, so if I immediately opened config manager, the projects where back in Release instead of debug.
Only after modifying the sln file and removing all the ActivceCfg lines I was able to have the configuration changes stick.
This is in VS2019.

**Comment by jeffkl** [comment]
One workaround is to specify which configuration you want SlnGen to use.

```
msbuild.exe /t:SlnGen /p:Configuration=Debug
```

It currently looks at conditions like `'$(Configuration)' == 'Release'"` to detect which values to use which is probably throwing it off.

**Comment by jeffkl** [comment]
Latest release will leave projects out of the build if they don’t support the selected solution platform/configuration.
